name: lotus-py35
channels: !!python/tuple
- defaults
- conda-forge
dependencies:
- numpy=1.11.2=py35_0
- pip=8.1.2=py35_0
- python=3.5.2=0
- wheel=0.29.0=py35_0
- setuptools=27.2.0=py35_0
- pip:
  - gym[atari]==0.8.1
  - pydot-ng==1.0.0
  - pytest==3.0.3
  - protobuf==3.2.0